export default {
  showFooter: true,
  isSidebarCompact: false,
  showBreadcrumb: true,
  menuAutoCollapsed: true,
  mode: 'light',
  layout: 'side',
  splitMenu: false,
  sideMode: 'light',
  isFooterAside: false,
  isSidebarFixed: true,
  isHeaderFixed: true,
  isUseTabsRouter: false,
  showHeader: true,
  brandTheme: '#0052D9',
  footerCompany: 'Tencent',
  footerIcp: '',
  appVersion: '',
  logoHeaderUrl: '',
  logoExpandedUrl: '',
  logoCollapsedUrl: '',
};
